; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ProFile Counter"
#define MyAppVersion "3.4"
#define MyAppPublisher "Ben Smith"
#define MyAppURL "https://bhs720.github.io/profile-counter"
#define MyAppExeName "ProFile Counter.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C18240FC-FAD5-49CF-A67E-8C6912F6F142}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir=.\releases\{#MyAppVersion}
OutputBaseFilename=ProFileCounterSetup{#MyAppVersion}
SetupIconFile=..\app\gui\tpcIcon.ico
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon={app}\tpcIcon.ico
UninstallDisplayName={#MyAppName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\app\x64\Release\ProFile Counter.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\app\x64\Release\pfc-tool.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\app\x64\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
; MainForm.resx ($this.Icon) and SettingsWindow.resx (panel1.BackgroundImage) are
; embedded as preserialized resources, so reading them back needs
; System.Resources.Extensions and its dependency closure. MainForm's
; InitializeComponent reads the icon, so omitting any of these does not degrade a
; feature -- the app fails to start.
Source: "..\app\x64\Release\System.Resources.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\app\x64\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\app\x64\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\app\x64\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\app\x64\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
; Not optional either, and newly required by the SDK-style build: the .resources headers name
; System.Resources.Extensions 4.0.0.0 while the shipped assembly is 8.0.0.0, and
; this config carries the binding redirect that reconciles them. Without it every
; form that owns a non-string resource throws FileLoadException on construction.
Source: "..\app\x64\Release\ProFile Counter.exe.config"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "..\app\gui\tpcIcon.ico"; DestDir: "{app}"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Flags: nowait postinstall skipifsilent; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"

[InstallDelete]
; Up to 3.3 the analyzer shipped as mupdf.exe. It was renamed to pfc-tool.exe,
; so an upgrade would otherwise strand the old 36 MB binary in {app} — and leave
; a second, older analyzer sitting next to the current one.
Type: files; Name: "{app}\mupdf.exe"

;Type: files; Name: "{localappdata}/ProFile Counter/UserSettings.xml"

[UninstallDelete]
Type: files; Name: "{localappdata}/ProFile Counter/UserSettings.xml"
Type: filesandordirs; Name: "{localappdata}/ProFile Counter"

